function makeUnitsFiles




folder = 'C:\Users\alanc\matlabProjects\HomeProjects_2025\TimeHistoryPlotter\+units';

out = getStuff();


for ii = 1:length(out)
    aa = {out{ii,:}};
    makeFile(aa, folder);

    bb = {aa{3}, aa{4}, aa{1}, aa{2}, 1/aa{5}};
    makeFile(bb, folder);
end




end
%% =======================================================================================
function makeFile(info, folder)

info{2} = strrep(info{2}, '/', '_per_');
info{4} = strrep(info{4}, '/', '_per_');


fileName = [info{2}, '_To_', info{4}];

% Open or create a text file for writing
fileID = fopen(fullfile(folder, [fileName, '.m']), 'w');

% Check if the file was opened successfully
if fileID == -1
    error('Cannot open file for writing.');
end

% Write some text to the file
fprintf(fileID, ['function out = ', fileName, '(inp)\n']);
fprintf(fileID, ['%% ' info{1}, ' to ', info{3}, ', k = ', num2str(info{5}), '\n']);
fprintf(fileID, '\n');
fprintf(fileID, ['out = ', num2str(info{5}), '.*inp;\n']);
fprintf(fileID, 'end\n');

% Close the file
fclose(fileID);

end
%% =======================================================================================
function out = getStuff()

out = { ...
    'inch', 'in', 'centimeter', 'cm', 2.54; ...
    'foot', 'ft', 'meter', 'm', 0.3048; ...
    'yard', 'yd', 'meter', 'm', 0.9144; ...
    'mile', 'mi', 'kilometer', 'km', 1.60934; ...
    'nautical mile', 'nmi', 'kilometer', 'km', 1.852; ...
    'millimeter', 'mm', 'inch', 'in', 0.0393701; ...
    'centimeter', 'cm', 'inch', 'in', 0.393701; ...
    'meter', 'm', 'yard', 'yd', 1.09361; ...
    'kilometer', 'km', 'mile', 'mi', 0.621371; ...
    'square inch', 'in2', 'square centimeter', 'cm2', 6.4516; ...
    'square foot', 'ft2', 'square meter', 'm2', 0.092903; ...
    'square yard', 'yd2', 'square meter', 'm2', 0.836127; ...
    'acre', 'ac', 'square meter', 'm2', 4046.86; ...
    'square mile', 'mi2', 'square kilometer', 'km2', 2.58999; ...
    'hectare', 'ha', 'acre', 'ac', 2.47105; ...
    'liter', 'L', 'gallon (US)', 'gal', 0.264172; ...
    'gallon (US)', 'gal', 'liter', 'L', 3.78541; ...
    'cup (US)', 'cup', 'milliliter', 'mL', 236.588; ...
    'tablespoon', 'tbsp', 'milliliter', 'mL', 14.7868; ...
    'teaspoon', 'tsp', 'milliliter', 'mL', 4.92892; ...
    'cubic inch', 'in3', 'cubic centimeter', 'cm3', 16.3871; ...
    'cubic foot', 'ft3', 'cubic meter', 'm3', 0.0283168; ...
    'cubic meter', 'm3', 'liter', 'L', 1000; ...
    'pound', 'lb', 'kilogram', 'kg', 0.453592; ...
    'ounce', 'oz', 'gram', 'g', 28.3495; ...
    'kilogram', 'kg', 'pound', 'lb', 2.20462; ...
    'gram', 'g', 'ounce', 'oz', 0.035274; ...
    'ton (US)', 'ton', 'kilogram', 'kg', 907.185; ...
    'stone (UK)', 'st', 'kilogram', 'kg', 6.35029; ...
    'minute', 'min', 'second', 's', 60; ...
    'hour', 'hr', 'minute', 'min', 60; ...
    'day', 'd', 'hour', 'hr', 24; ...
    'week', 'wk', 'day', 'd', 7; ...
    'year', 'yr', 'day', 'd', 365.25; ...
    'mile per hour', 'mph', 'kilometer per hour', 'km/h', 1.60934; ...
    'meter per second', 'm/s', 'kilometer per hour', 'km/h', 3.6; ...
    'kilometer per hour', 'km/h', 'meter per second', 'm/s', 0.277778; ...
    'atmosphere', 'atm', 'pascal', 'Pa', 101325; ...
    'psi', 'psi', 'pascal', 'Pa', 6894.76; ...
    'bar', 'bar', 'pascal', 'Pa', 100000; ...
    'mmHg', 'mmHg', 'pascal', 'Pa', 133.322; ...
    'joule', 'J', 'newton meter', 'N·m', 1; ...
    'calorie', 'cal', 'joule', 'J', 4.184; ...
    'kilocalorie', 'kcal', 'joule', 'J', 4184; ...
    'BTU', 'BTU', 'joule', 'J', 1055.06; ...
    'kilowatt hour', 'kWh', 'joule', 'J', 3.6e6; ...
    'horsepower', 'hp', 'watt', 'W', 745.7; ...
    'kilowatt', 'kW', 'watt', 'W', 1000};

end
%% =======================================================================================